"""add core domain models

Revision ID: 44421f096dc9
Revises: b4b50aa2f210
Create Date: 2026-08-29 16:25:24.047823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44421f096dc9'
down_revision: Union[str, None] = 'b4b50aa2f210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freedom_funds_pct', sa.Integer(), nullable=False),
    sa.Column('essentials_pct', sa.Integer(), nullable=False),
    sa.Column('lifestyle_pct', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('freedom_funds_pct + essentials_pct + lifestyle_pct = 100', name='budget_split_sums_to_100'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bucket', sa.Enum('ESSENTIALS', 'LIFESTYLE', name='budget_bucket'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('balance_cents', sa.BigInteger(), nullable=False),
    sa.Column('monthly_payment_cents', sa.BigInteger(), nullable=False),
    sa.Column('payoff_target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency_fund_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('multiplier >= 3 AND multiplier <= 6', name='ef_multiplier_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('FIXED', 'FREELANCE', name='income_source'), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_mode_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('FIXED_ONLY', 'FIXED_PLUS_FREELANCE', 'FREELANCE_ONLY', name='income_mode'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    op.drop_table('income_mode_config')
    op.drop_table('income_entries')
    op.drop_table('emergency_fund_config')
    op.drop_table('debts')
    op.drop_table('categories')
    op.drop_table('budget_splits')
    # ### end Alembic commands ###
