"""add fixed salary to income mode config

Revision ID: d4e59511e331
Revises: 83368cad6ad7
Create Date: 2026-09-07 00:26:48.879403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e59511e331'
down_revision: Union[str, None] = '83368cad6ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income_mode_config', sa.Column('fixed_salary_cents', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income_mode_config', 'fixed_salary_cents')
    # ### end Alembic commands ###
