"""remove obsolete freedom funds allocation

Revision ID: dc3a4b774095
Revises: 8f006702d24e
Create Date: 2026-09-20 13:37:51.777070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc3a4b774095'
down_revision: Union[str, None] = '8f006702d24e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('freedom_funds_allocation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freedom_funds_allocation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('investments_pct', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('debt_pct', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(investments_pct + debt_pct) = 100', name='ff_allocation_sums_to_100'),
    sa.PrimaryKeyConstraint('id', name='freedom_funds_allocation_pkey')
    )
    # ### end Alembic commands ###
