"""phase 6: frozen EF target, freedom funds allocation

Revision ID: e0189c55a75f
Revises: 44421f096dc9
Create Date: 2026-09-05 13:45:59.688670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0189c55a75f'
down_revision: Union[str, None] = '44421f096dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freedom_funds_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investments_pct', sa.Integer(), nullable=False),
    sa.Column('debt_pct', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('investments_pct + debt_pct = 100', name='ff_allocation_sums_to_100'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('emergency_fund_config', sa.Column('estimated_monthly_income_cents', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('emergency_fund_config', sa.Column('target_cents', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('emergency_fund_config', sa.Column('current_balance_cents', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergency_fund_config', 'current_balance_cents')
    op.drop_column('emergency_fund_config', 'target_cents')
    op.drop_column('emergency_fund_config', 'estimated_monthly_income_cents')
    op.drop_table('freedom_funds_allocation')
    # ### end Alembic commands ###
